/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views2;

import Models.Admin;
import Models.Conductor;
import java.awt.Color;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import kotlin.random.Random;

/**
 *
 * @author Mihae
 */
public class AdminConductoresPanel extends javax.swing.JPanel {

    /**
     * Creates new form ConductoresAdmin
     */
    Admin admin;
    public AdminConductoresPanel(Admin admin) {
        this.admin = admin;
        initComponents();
        correcciones_iniciales();
    }
    
    private void correcciones_iniciales(){
        dni_buscar_input.setBackground(new Color(168, 168, 168));
        dni_eliminar_input.setBackground(new Color(168, 168, 168));
        
        tabla_conductores.getColumnModel().getColumn(0).setPreferredWidth(10);
        tabla_conductores.setBackground(new Color(230, 230, 230));
        tabla_datos_conductor.getColumnModel().getColumn(0).setPreferredWidth(10);
        tabla_datos_conductor.setBackground(new Color(230, 230, 230));
    }
    
    private void listar_conductores(){
        DefaultTableModel modelo = (DefaultTableModel)tabla_conductores.getModel();
        modelo.setRowCount(0);
        
        List<Conductor> conductores = admin.ver_conductores();
        for(Conductor conductor:conductores){
            modelo.addRow(new Object[]{conductor.get_dni(), conductor.get_correo(), conductor.get_departamento()});
        }
        
        tabla_conductores.setModel(modelo);
    }
    
    private void ver_datos_conductor(){
        DefaultTableModel modelo = (DefaultTableModel)tabla_datos_conductor.getModel();
        modelo.setRowCount(0);
        
        String dni = dni_buscar_input.getText();
        Conductor conductor = admin.buscar_conductor(dni);
        
        if(conductor==null){
            modelo.addRow(new Object[]{"ERROR", "DNI NO EXISTE"});
        } else {
            modelo.addRow(new Object[]{"DNI", conductor.get_dni()});
            modelo.addRow(new Object[]{"Nombres", conductor.get_nombre()});
            modelo.addRow(new Object[]{"Correo", conductor.get_correo()});
            modelo.addRow(new Object[]{"Fecha de Nacimiento", conductor.get_fecha_nacimiento()});
            modelo.addRow(new Object[]{"Distrito", conductor.get_distrito()});
            modelo.addRow(new Object[]{"Provincia", conductor.get_provincia()});
            modelo.addRow(new Object[]{"Departamento", conductor.get_departamento()});
            modelo.addRow(new Object[]{"Dias de Descanso", conductor.get_dias_descanso()});
            modelo.addRow(new Object[]{"Contraseña", conductor.get_contrasena()});
        }
        
        tabla_datos_conductor.setModel(modelo);
    }
    
    private void eliminar_conductor(){
        String dni = dni_eliminar_input.getText();
        boolean exito = admin.eliminar_conductor(dni);
        if(!exito){
            resultado_eliminar.setText("No se pudo borrar");
            return;
        }
        resultado_eliminar.setText("Conductor eliminado!!");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        buscar_conductor_button = new javax.swing.JButton();
        dni_buscar_input = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dni_eliminar_input = new javax.swing.JTextField();
        eliminar_conductor_button = new javax.swing.JButton();
        resultado_eliminar = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_conductores = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_datos_conductor = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1010, 580));
        setPreferredSize(new java.awt.Dimension(1010, 580));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(23, 23, 23));
        jLabel1.setText("Listado de Conductores");

        jButton1.setBackground(new java.awt.Color(30, 30, 30));
        jButton1.setForeground(new java.awt.Color(245, 245, 245));
        jButton1.setText("Listar Conductores");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        jButton1.setMaximumSize(new java.awt.Dimension(170, 40));
        jButton1.setPreferredSize(new java.awt.Dimension(170, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(23, 23, 23));
        jLabel2.setText("Buscar Conductor por DNI");

        buscar_conductor_button.setBackground(new java.awt.Color(30, 30, 30));
        buscar_conductor_button.setForeground(new java.awt.Color(245, 245, 245));
        buscar_conductor_button.setText("Buscar Conductor");
        buscar_conductor_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        buscar_conductor_button.setMaximumSize(new java.awt.Dimension(161, 40));
        buscar_conductor_button.setMinimumSize(new java.awt.Dimension(161, 40));
        buscar_conductor_button.setPreferredSize(new java.awt.Dimension(161, 40));
        buscar_conductor_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_conductor_buttonActionPerformed(evt);
            }
        });

        dni_buscar_input.setCaretColor(new java.awt.Color(168, 168, 168));

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(23, 23, 23));
        jLabel3.setText("Eliminar Conductor por DNI");

        eliminar_conductor_button.setBackground(new java.awt.Color(30, 30, 30));
        eliminar_conductor_button.setForeground(new java.awt.Color(245, 245, 245));
        eliminar_conductor_button.setText("Eliminar Conductor");
        eliminar_conductor_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        eliminar_conductor_button.setMaximumSize(new java.awt.Dimension(161, 40));
        eliminar_conductor_button.setMinimumSize(new java.awt.Dimension(161, 40));
        eliminar_conductor_button.setPreferredSize(new java.awt.Dimension(161, 40));
        eliminar_conductor_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_conductor_buttonActionPerformed(evt);
            }
        });

        resultado_eliminar.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        resultado_eliminar.setForeground(new java.awt.Color(44, 73, 168));

        jButton4.setBackground(new java.awt.Color(30, 30, 30));
        jButton4.setForeground(new java.awt.Color(245, 245, 245));
        jButton4.setText("Agregar Conductor");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        jButton4.setMaximumSize(new java.awt.Dimension(161, 40));
        jButton4.setMinimumSize(new java.awt.Dimension(161, 40));
        jButton4.setPreferredSize(new java.awt.Dimension(161, 40));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tabla_conductores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "Correo", "Departamento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla_conductores);

        tabla_datos_conductor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dato", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabla_datos_conductor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(buscar_conductor_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dni_buscar_input)
                                    .addComponent(jLabel3)
                                    .addComponent(dni_eliminar_input)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(eliminar_conductor_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(resultado_eliminar))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(dni_buscar_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscar_conductor_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dni_eliminar_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eliminar_conductor_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resultado_eliminar))
                        .addGap(46, 46, 46)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        listar_conductores();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buscar_conductor_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_conductor_buttonActionPerformed
       ver_datos_conductor();
    }//GEN-LAST:event_buscar_conductor_buttonActionPerformed

    private void eliminar_conductor_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_conductor_buttonActionPerformed
        eliminar_conductor();
    }//GEN-LAST:event_eliminar_conductor_buttonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        AdminConductorCrear crear_conductor = new AdminConductorCrear(admin);
        crear_conductor.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar_conductor_button;
    private javax.swing.JTextField dni_buscar_input;
    private javax.swing.JTextField dni_eliminar_input;
    private javax.swing.JButton eliminar_conductor_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel resultado_eliminar;
    private javax.swing.JTable tabla_conductores;
    private javax.swing.JTable tabla_datos_conductor;
    // End of variables declaration//GEN-END:variables
}
