
package Vista;

import Models.Admin;
import Views2.AdminConductoresPanel;
import Views2.Destinos;
import Views2.IniciarSesionPrincipal;
import Views2.Inicio;
import Views2.Nosotros;
import Views2.AdminPerfilPanel;
import Views2.AdminRutasPanel;
import java.awt.BorderLayout;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JPanel;

/**
 *
 * @author USER
 */
public class DashboardAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    
    private Admin admin;
    
    public DashboardAdmin(Admin admin) {
        this.admin = admin;
        initComponents();
        setDate();
        initContent();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    private void setDate(){
        LocalDate now= LocalDate.now();
        Locale spanishLocale = new Locale ( "es", "ES");
        fecha.setText(now.format(DateTimeFormatter.ofPattern("'Hoy es' EEEE dd 'de' MMMM 'de' yyyy", spanishLocale)));
    }
    
    private void initContent(){
        ShowJPanel(new Inicio());
        ShowJPanel(new Nosotros());
        ShowJPanel(new Destinos());
    }
    public void ShowJPanel(JPanel in){
        in.setSize(1010, 580);
        in.setLocation(0, 0);
        content.removeAll();
        content.add(in, BorderLayout.CENTER);
        content.revalidate();
        content.repaint(); 
    }
    
    /*private void ShowJPanel(JPanel n){
        n.setSize(1010, 580);
        n.setLocation(0, 0);
        content.removeAll();
        content.add(n, BorderLayout.CENTER);
        content.revalidate();
        content.repaint(); 
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jPanelConEncabezadoColectivo1 = new Vista.JPanelConEncabezadoColectivo();
        menu = new javax.swing.JPanel();
        perfil_button = new javax.swing.JButton();
        rutas_button = new javax.swing.JButton();
        conductores_button = new javax.swing.JButton();
        regulacion_button = new javax.swing.JButton();
        pasajeros_button = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        fecha = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 620));

        jPanelConEncabezadoColectivo1.setPreferredSize(new java.awt.Dimension(1280, 90));

        javax.swing.GroupLayout jPanelConEncabezadoColectivo1Layout = new javax.swing.GroupLayout(jPanelConEncabezadoColectivo1);
        jPanelConEncabezadoColectivo1.setLayout(jPanelConEncabezadoColectivo1Layout);
        jPanelConEncabezadoColectivo1Layout.setHorizontalGroup(
            jPanelConEncabezadoColectivo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelConEncabezadoColectivo1Layout.setVerticalGroup(
            jPanelConEncabezadoColectivo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        menu.setBackground(new java.awt.Color(0, 0, 204));

        perfil_button.setBackground(new java.awt.Color(0,0,0,0));
        perfil_button.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        perfil_button.setForeground(new java.awt.Color(255, 255, 255));
        perfil_button.setText("PERFIL");
        perfil_button.setBorder(null);
        perfil_button.setBorderPainted(false);
        perfil_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        perfil_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfil_buttonActionPerformed(evt);
            }
        });

        rutas_button.setBackground(new java.awt.Color(0,0,0,0));
        rutas_button.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        rutas_button.setForeground(new java.awt.Color(255, 255, 255));
        rutas_button.setText("RUTAS");
        rutas_button.setBorder(null);
        rutas_button.setBorderPainted(false);
        rutas_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rutas_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutas_buttonActionPerformed(evt);
            }
        });

        conductores_button.setBackground(new java.awt.Color(0,0,0,0));
        conductores_button.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        conductores_button.setForeground(new java.awt.Color(255, 255, 255));
        conductores_button.setText("CONDUCTORES");
        conductores_button.setBorder(null);
        conductores_button.setBorderPainted(false);
        conductores_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        conductores_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conductores_buttonActionPerformed(evt);
            }
        });

        regulacion_button.setBackground(new java.awt.Color(0,0,0,0));
        regulacion_button.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        regulacion_button.setForeground(new java.awt.Color(255, 255, 255));
        regulacion_button.setText("REGULACION LABORAL");
        regulacion_button.setBorder(null);
        regulacion_button.setBorderPainted(false);
        regulacion_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regulacion_button.setMargin(new java.awt.Insets(0, 14, 2, 14));
        regulacion_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regulacion_buttonActionPerformed(evt);
            }
        });

        pasajeros_button.setBackground(new java.awt.Color(0,0,0,0));
        pasajeros_button.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        pasajeros_button.setForeground(new java.awt.Color(255, 255, 255));
        pasajeros_button.setText("PASAJEROS");
        pasajeros_button.setBorder(null);
        pasajeros_button.setBorderPainted(false);
        pasajeros_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pasajeros_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasajeros_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(perfil_button, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conductores_button, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rutas_button, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(pasajeros_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(regulacion_button, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(perfil_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conductores_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rutas_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pasajeros_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regulacion_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        header.setBackground(new java.awt.Color(0, 153, 255));

        fecha.setBackground(new java.awt.Color(255, 255, 255));
        fecha.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setText("Hoy es {dayname} {day} de {month} del {year}");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        content.setBackground(new java.awt.Color(0, 0, 0));
        content.setPreferredSize(new java.awt.Dimension(1010, 580));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelConEncabezadoColectivo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelConEncabezadoColectivo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pasajeros_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasajeros_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pasajeros_buttonActionPerformed

    private void regulacion_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regulacion_buttonActionPerformed
        ShowJPanel(new Nosotros());
    }//GEN-LAST:event_regulacion_buttonActionPerformed

    private void conductores_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conductores_buttonActionPerformed
        ShowJPanel(new AdminConductoresPanel(admin));
    }//GEN-LAST:event_conductores_buttonActionPerformed

    private void rutas_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutas_buttonActionPerformed
        ShowJPanel(new AdminRutasPanel(admin));
    }//GEN-LAST:event_rutas_buttonActionPerformed

    private void perfil_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfil_buttonActionPerformed
        ShowJPanel(new AdminPerfilPanel(admin));
    }//GEN-LAST:event_perfil_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new DashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton conductores_button;
    private javax.swing.JPanel content;
    private javax.swing.JLabel fecha;
    private javax.swing.JPanel header;
    private Vista.JPanelConEncabezadoColectivo jPanelConEncabezadoColectivo1;
    private javax.swing.JPanel menu;
    private javax.swing.JButton pasajeros_button;
    private javax.swing.JButton perfil_button;
    private javax.swing.JButton regulacion_button;
    private javax.swing.JButton rutas_button;
    // End of variables declaration//GEN-END:variables
}
